// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: proto/linetype/v1/linetype.proto

package linetypev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LineClass mirrors the Class enum in linetype.go.
type LineClass int32

const (
	LineClass_LINE_CLASS_UNSPECIFIED LineClass = 0
	LineClass_LINE_CLASS_WIRELINE    LineClass = 1
	LineClass_LINE_CLASS_WIRELESS    LineClass = 2
	LineClass_LINE_CLASS_VOIP        LineClass = 3
	LineClass_LINE_CLASS_TOLLFREE    LineClass = 4
	LineClass_LINE_CLASS_INVALID     LineClass = 5
)

// Enum value maps for LineClass.
var (
	LineClass_name = map[int32]string{
		0: "LINE_CLASS_UNSPECIFIED",
		1: "LINE_CLASS_WIRELINE",
		2: "LINE_CLASS_WIRELESS",
		3: "LINE_CLASS_VOIP",
		4: "LINE_CLASS_TOLLFREE",
		5: "LINE_CLASS_INVALID",
	}
	LineClass_value = map[string]int32{
		"LINE_CLASS_UNSPECIFIED": 0,
		"LINE_CLASS_WIRELINE":    1,
		"LINE_CLASS_WIRELESS":    2,
		"LINE_CLASS_VOIP":        3,
		"LINE_CLASS_TOLLFREE":    4,
		"LINE_CLASS_INVALID":     5,
	}
)

func (x LineClass) Enum() *LineClass {
	p := new(LineClass)
	*p = x
	return p
}

func (x LineClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LineClass) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_linetype_v1_linetype_proto_enumTypes[0].Descriptor()
}

func (LineClass) Type() protoreflect.EnumType {
	return &file_proto_linetype_v1_linetype_proto_enumTypes[0]
}

func (x LineClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LineClass.Descriptor instead.
func (LineClass) EnumDescriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{0}
}

// CarrierInfo identifies the company holding a number range.
type CarrierInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operating company number, e.g. "6529".
	Ocn string `protobuf:"bytes,1,opt,name=ocn,proto3" json:"ocn,omitempty"`
	// Published company name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional human-facing brand.
	Brand         string `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarrierInfo) Reset() {
	*x = CarrierInfo{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierInfo) ProtoMessage() {}

func (x *CarrierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierInfo.ProtoReflect.Descriptor instead.
func (*CarrierInfo) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{0}
}

func (x *CarrierInfo) GetOcn() string {
	if x != nil {
		return x.Ocn
	}
	return ""
}

func (x *CarrierInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CarrierInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

// RegionInfo identifies the geography of a number range.
type RegionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State/province code, e.g. "MO", "ON".
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// ISO 3166-1 alpha-2, e.g. "US", "CA".
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// Full country name.
	Country       string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionInfo) Reset() {
	*x = RegionInfo{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfo) ProtoMessage() {}

func (x *RegionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfo.ProtoReflect.Descriptor instead.
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{1}
}

func (x *RegionInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegionInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *RegionInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// ClassTable holds nibble-packed US/CA line type data.
// Index = (NPA*10000 + NXX*10 + Block) - 2000000.
// Low nibble = even index, high nibble = odd index.
type ClassTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly 4,000,000 bytes.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassTable) Reset() {
	*x = ClassTable{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassTable) ProtoMessage() {}

func (x *ClassTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassTable.ProtoReflect.Descriptor instead.
func (*ClassTable) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{2}
}

func (x *ClassTable) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// CarrierException is a block-level carrier override.
type CarrierException struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NXX offset from 200000 (0..799999).
	NxxOffset uint32 `protobuf:"varint,1,opt,name=nxx_offset,json=nxxOffset,proto3" json:"nxx_offset,omitempty"`
	// Block digit 0-9.
	Block uint32 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	// Index into CarrierTable.carriers.
	CarrierIndex  uint32 `protobuf:"varint,3,opt,name=carrier_index,json=carrierIndex,proto3" json:"carrier_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarrierException) Reset() {
	*x = CarrierException{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierException) ProtoMessage() {}

func (x *CarrierException) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierException.ProtoReflect.Descriptor instead.
func (*CarrierException) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{3}
}

func (x *CarrierException) GetNxxOffset() uint32 {
	if x != nil {
		return x.NxxOffset
	}
	return 0
}

func (x *CarrierException) GetBlock() uint32 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *CarrierException) GetCarrierIndex() uint32 {
	if x != nil {
		return x.CarrierIndex
	}
	return 0
}

// CarrierTable maps US/CA blocks to their holding carrier.
// Uses NXX-base plus sparse exceptions.
type CarrierTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1,600,000 bytes; uint16 LE per NXX.
	NxxBase []byte `protobuf:"bytes,1,opt,name=nxx_base,json=nxxBase,proto3" json:"nxx_base,omitempty"`
	// Sorted by (nxx_offset*10 + block).
	Exceptions []*CarrierException `protobuf:"bytes,2,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	// Index 0 = unknown/no carrier on file.
	Carriers      []*CarrierInfo `protobuf:"bytes,3,rep,name=carriers,proto3" json:"carriers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarrierTable) Reset() {
	*x = CarrierTable{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierTable) ProtoMessage() {}

func (x *CarrierTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierTable.ProtoReflect.Descriptor instead.
func (*CarrierTable) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{4}
}

func (x *CarrierTable) GetNxxBase() []byte {
	if x != nil {
		return x.NxxBase
	}
	return nil
}

func (x *CarrierTable) GetExceptions() []*CarrierException {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

func (x *CarrierTable) GetCarriers() []*CarrierInfo {
	if x != nil {
		return x.Carriers
	}
	return nil
}

// RegionTable maps US/CA NXXs to their geographic region.
type RegionTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 800,000 bytes; 1 byte per NXX.
	NxxIndex []byte `protobuf:"bytes,1,opt,name=nxx_index,json=nxxIndex,proto3" json:"nxx_index,omitempty"`
	// Index 0 = unknown/no region on file.
	Regions       []*RegionInfo `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionTable) Reset() {
	*x = RegionTable{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionTable) ProtoMessage() {}

func (x *RegionTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionTable.ProtoReflect.Descriptor instead.
func (*RegionTable) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{5}
}

func (x *RegionTable) GetNxxIndex() []byte {
	if x != nil {
		return x.NxxIndex
	}
	return nil
}

func (x *RegionTable) GetRegions() []*RegionInfo {
	if x != nil {
		return x.Regions
	}
	return nil
}

// MXRange is a single Mexico number range.
type MXRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First number, e.g. 5512340000.
	Start uint64 `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	// Last number, inclusive.
	End uint64 `protobuf:"fixed64,2,opt,name=end,proto3" json:"end,omitempty"`
	// Line class for this range.
	LineClass LineClass `protobuf:"varint,3,opt,name=line_class,json=lineClass,proto3,enum=linetype.v1.LineClass" json:"line_class,omitempty"`
	// Index into MXTable.carriers.
	CarrierIndex  uint32 `protobuf:"varint,4,opt,name=carrier_index,json=carrierIndex,proto3" json:"carrier_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MXRange) Reset() {
	*x = MXRange{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MXRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MXRange) ProtoMessage() {}

func (x *MXRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MXRange.ProtoReflect.Descriptor instead.
func (*MXRange) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{6}
}

func (x *MXRange) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *MXRange) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *MXRange) GetLineClass() LineClass {
	if x != nil {
		return x.LineClass
	}
	return LineClass_LINE_CLASS_UNSPECIFIED
}

func (x *MXRange) GetCarrierIndex() uint32 {
	if x != nil {
		return x.CarrierIndex
	}
	return 0
}

// MXBucket narrows binary search to a 3-digit prefix.
type MXBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First range index for this prefix.
	StartIndex uint32 `protobuf:"varint,1,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	// One past last range index.
	EndIndex      uint32 `protobuf:"varint,2,opt,name=end_index,json=endIndex,proto3" json:"end_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MXBucket) Reset() {
	*x = MXBucket{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MXBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MXBucket) ProtoMessage() {}

func (x *MXBucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MXBucket.ProtoReflect.Descriptor instead.
func (*MXBucket) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{7}
}

func (x *MXBucket) GetStartIndex() uint32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *MXBucket) GetEndIndex() uint32 {
	if x != nil {
		return x.EndIndex
	}
	return 0
}

// MXTable holds Mexico (+52) range data with prefix index.
type MXTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sorted by start.
	Ranges []*MXRange `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	// 800 buckets for prefixes 200..999.
	PrefixIndices []*MXBucket `protobuf:"bytes,2,rep,name=prefix_indices,json=prefixIndices,proto3" json:"prefix_indices,omitempty"`
	// Index 0 = unknown.
	Carriers      []*CarrierInfo `protobuf:"bytes,3,rep,name=carriers,proto3" json:"carriers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MXTable) Reset() {
	*x = MXTable{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MXTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MXTable) ProtoMessage() {}

func (x *MXTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MXTable.ProtoReflect.Descriptor instead.
func (*MXTable) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{8}
}

func (x *MXTable) GetRanges() []*MXRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *MXTable) GetPrefixIndices() []*MXBucket {
	if x != nil {
		return x.PrefixIndices
	}
	return nil
}

func (x *MXTable) GetCarriers() []*CarrierInfo {
	if x != nil {
		return x.Carriers
	}
	return nil
}

// PhoneData is the top-level container for all lookup tables.
// Serialized as a single file (e.g. data/phone_data.pb).
type PhoneData struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClassTable   *ClassTable            `protobuf:"bytes,1,opt,name=class_table,json=classTable,proto3" json:"class_table,omitempty"`
	CarrierTable *CarrierTable          `protobuf:"bytes,2,opt,name=carrier_table,json=carrierTable,proto3" json:"carrier_table,omitempty"`
	RegionTable  *RegionTable           `protobuf:"bytes,3,opt,name=region_table,json=regionTable,proto3" json:"region_table,omitempty"`
	MxTable      *MXTable               `protobuf:"bytes,4,opt,name=mx_table,json=mxTable,proto3" json:"mx_table,omitempty"`
	// RFC 3339 build timestamp.
	BuildDate string `protobuf:"bytes,10,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	// Data format version.
	Version       string `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneData) Reset() {
	*x = PhoneData{}
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneData) ProtoMessage() {}

func (x *PhoneData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_linetype_v1_linetype_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneData.ProtoReflect.Descriptor instead.
func (*PhoneData) Descriptor() ([]byte, []int) {
	return file_proto_linetype_v1_linetype_proto_rawDescGZIP(), []int{9}
}

func (x *PhoneData) GetClassTable() *ClassTable {
	if x != nil {
		return x.ClassTable
	}
	return nil
}

func (x *PhoneData) GetCarrierTable() *CarrierTable {
	if x != nil {
		return x.CarrierTable
	}
	return nil
}

func (x *PhoneData) GetRegionTable() *RegionTable {
	if x != nil {
		return x.RegionTable
	}
	return nil
}

func (x *PhoneData) GetMxTable() *MXTable {
	if x != nil {
		return x.MxTable
	}
	return nil
}

func (x *PhoneData) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *PhoneData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_linetype_v1_linetype_proto protoreflect.FileDescriptor

const file_proto_linetype_v1_linetype_proto_rawDesc = "" +
	"\n" +
	" proto/linetype/v1/linetype.proto\x12\vlinetype.v1\"I\n" +
	"\vCarrierInfo\x12\x10\n" +
	"\x03ocn\x18\x01 \x01(\tR\x03ocn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\"]\n" +
	"\n" +
	"RegionInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\" \n" +
	"\n" +
	"ClassTable\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"l\n" +
	"\x10CarrierException\x12\x1d\n" +
	"\n" +
	"nxx_offset\x18\x01 \x01(\rR\tnxxOffset\x12\x14\n" +
	"\x05block\x18\x02 \x01(\rR\x05block\x12#\n" +
	"\rcarrier_index\x18\x03 \x01(\rR\fcarrierIndex\"\x9e\x01\n" +
	"\fCarrierTable\x12\x19\n" +
	"\bnxx_base\x18\x01 \x01(\fR\anxxBase\x12=\n" +
	"\n" +
	"exceptions\x18\x02 \x03(\v2\x1d.linetype.v1.CarrierExceptionR\n" +
	"exceptions\x124\n" +
	"\bcarriers\x18\x03 \x03(\v2\x18.linetype.v1.CarrierInfoR\bcarriers\"]\n" +
	"\vRegionTable\x12\x1b\n" +
	"\tnxx_index\x18\x01 \x01(\fR\bnxxIndex\x121\n" +
	"\aregions\x18\x02 \x03(\v2\x17.linetype.v1.RegionInfoR\aregions\"\x8d\x01\n" +
	"\aMXRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x06R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x06R\x03end\x125\n" +
	"\n" +
	"line_class\x18\x03 \x01(\x0e2\x16.linetype.v1.LineClassR\tlineClass\x12#\n" +
	"\rcarrier_index\x18\x04 \x01(\rR\fcarrierIndex\"H\n" +
	"\bMXBucket\x12\x1f\n" +
	"\vstart_index\x18\x01 \x01(\rR\n" +
	"startIndex\x12\x1b\n" +
	"\tend_index\x18\x02 \x01(\rR\bendIndex\"\xab\x01\n" +
	"\aMXTable\x12,\n" +
	"\x06ranges\x18\x01 \x03(\v2\x14.linetype.v1.MXRangeR\x06ranges\x12<\n" +
	"\x0eprefix_indices\x18\x02 \x03(\v2\x15.linetype.v1.MXBucketR\rprefixIndices\x124\n" +
	"\bcarriers\x18\x03 \x03(\v2\x18.linetype.v1.CarrierInfoR\bcarriers\"\xac\x02\n" +
	"\tPhoneData\x128\n" +
	"\vclass_table\x18\x01 \x01(\v2\x17.linetype.v1.ClassTableR\n" +
	"classTable\x12>\n" +
	"\rcarrier_table\x18\x02 \x01(\v2\x19.linetype.v1.CarrierTableR\fcarrierTable\x12;\n" +
	"\fregion_table\x18\x03 \x01(\v2\x18.linetype.v1.RegionTableR\vregionTable\x12/\n" +
	"\bmx_table\x18\x04 \x01(\v2\x14.linetype.v1.MXTableR\amxTable\x12\x1d\n" +
	"\n" +
	"build_date\x18\n" +
	" \x01(\tR\tbuildDate\x12\x18\n" +
	"\aversion\x18\v \x01(\tR\aversion*\x9f\x01\n" +
	"\tLineClass\x12\x1a\n" +
	"\x16LINE_CLASS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13LINE_CLASS_WIRELINE\x10\x01\x12\x17\n" +
	"\x13LINE_CLASS_WIRELESS\x10\x02\x12\x13\n" +
	"\x0fLINE_CLASS_VOIP\x10\x03\x12\x17\n" +
	"\x13LINE_CLASS_TOLLFREE\x10\x04\x12\x16\n" +
	"\x12LINE_CLASS_INVALID\x10\x05BOZMgithub.com/tomba-io/phone-line-type-intelligence/proto/linetype/v1;linetypev1b\x06proto3"

var (
	file_proto_linetype_v1_linetype_proto_rawDescOnce sync.Once
	file_proto_linetype_v1_linetype_proto_rawDescData []byte
)

func file_proto_linetype_v1_linetype_proto_rawDescGZIP() []byte {
	file_proto_linetype_v1_linetype_proto_rawDescOnce.Do(func() {
		file_proto_linetype_v1_linetype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_linetype_v1_linetype_proto_rawDesc), len(file_proto_linetype_v1_linetype_proto_rawDesc)))
	})
	return file_proto_linetype_v1_linetype_proto_rawDescData
}

var file_proto_linetype_v1_linetype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_linetype_v1_linetype_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_linetype_v1_linetype_proto_goTypes = []any{
	(LineClass)(0),           // 0: linetype.v1.LineClass
	(*CarrierInfo)(nil),      // 1: linetype.v1.CarrierInfo
	(*RegionInfo)(nil),       // 2: linetype.v1.RegionInfo
	(*ClassTable)(nil),       // 3: linetype.v1.ClassTable
	(*CarrierException)(nil), // 4: linetype.v1.CarrierException
	(*CarrierTable)(nil),     // 5: linetype.v1.CarrierTable
	(*RegionTable)(nil),      // 6: linetype.v1.RegionTable
	(*MXRange)(nil),          // 7: linetype.v1.MXRange
	(*MXBucket)(nil),         // 8: linetype.v1.MXBucket
	(*MXTable)(nil),          // 9: linetype.v1.MXTable
	(*PhoneData)(nil),        // 10: linetype.v1.PhoneData
}
var file_proto_linetype_v1_linetype_proto_depIdxs = []int32{
	4,  // 0: linetype.v1.CarrierTable.exceptions:type_name -> linetype.v1.CarrierException
	1,  // 1: linetype.v1.CarrierTable.carriers:type_name -> linetype.v1.CarrierInfo
	2,  // 2: linetype.v1.RegionTable.regions:type_name -> linetype.v1.RegionInfo
	0,  // 3: linetype.v1.MXRange.line_class:type_name -> linetype.v1.LineClass
	7,  // 4: linetype.v1.MXTable.ranges:type_name -> linetype.v1.MXRange
	8,  // 5: linetype.v1.MXTable.prefix_indices:type_name -> linetype.v1.MXBucket
	1,  // 6: linetype.v1.MXTable.carriers:type_name -> linetype.v1.CarrierInfo
	3,  // 7: linetype.v1.PhoneData.class_table:type_name -> linetype.v1.ClassTable
	5,  // 8: linetype.v1.PhoneData.carrier_table:type_name -> linetype.v1.CarrierTable
	6,  // 9: linetype.v1.PhoneData.region_table:type_name -> linetype.v1.RegionTable
	9,  // 10: linetype.v1.PhoneData.mx_table:type_name -> linetype.v1.MXTable
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_linetype_v1_linetype_proto_init() }
func file_proto_linetype_v1_linetype_proto_init() {
	if File_proto_linetype_v1_linetype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_linetype_v1_linetype_proto_rawDesc), len(file_proto_linetype_v1_linetype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_linetype_v1_linetype_proto_goTypes,
		DependencyIndexes: file_proto_linetype_v1_linetype_proto_depIdxs,
		EnumInfos:         file_proto_linetype_v1_linetype_proto_enumTypes,
		MessageInfos:      file_proto_linetype_v1_linetype_proto_msgTypes,
	}.Build()
	File_proto_linetype_v1_linetype_proto = out.File
	file_proto_linetype_v1_linetype_proto_goTypes = nil
	file_proto_linetype_v1_linetype_proto_depIdxs = nil
}
